# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

version: "3.6"
services:
  tes:
    container_name: lab1_tes
    environment:
      - LAB_NAME=LABNAME
      - DefaultStorageAccountName=STORAGEACCOUNTNAME
  mysqldb:
    container_name: lab1_mysqldb
    volumes:
      - type: bind
        source: /mysql-1
        target: /var/lib/mysql
  cromwell:
    container_name: lab1_cromwell
    volumes:
      - type: bind
        source: /cromwell-workflow-logs-1
        target: /cromwell-workflow-logs
      - type: bind
        source: /cromwell-executions-1
        target: /cromwell-executions
      - type: bind
        source: /inputs-1
        target: /STORAGEACCOUNTNAME/inputs
  triggerservice:
    container_name: lab1_triggerservice
    environment:
      - LAB_NAME=LABNAME
      - DefaultStorageAccountName=STORAGEACCOUNTNAME